# qkd/type_defs.py
# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Protocol, Union, runtime_checkable
import numpy as np


@runtime_checkable
class RNGProtocol(Protocol):
    def random(self, size=None) -> Union[float, np.ndarray]: ...
    def normal(self, loc=0.0, scale=1.0, size=None) -> Union[float, np.ndarray]: ...
    def poisson(self, lam=1.0, size=None) -> Union[int, np.ndarray]: ...
    def gamma(self, shape, scale=1.0, size=None) -> Union[float, np.ndarray]: ...
    def lognormal(self, mean=0.0, sigma=1.0, size=None) -> Union[float, np.ndarray]: ...
    def geometric(self, p, size=None) -> Union[int, np.ndarray]: ...
    def choice(self, a, size=None, replace=True, p=None): ...


RNGType = RNGProtocol

